---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kustomize-monitoring
  namespace: flux-system
spec:
  interval: 1h0m0s
  path: ./monitoring/configs/dashboards
  prune: true
  sourceRef:
    kind: GitRepository
    name: monitoring-habibul
