---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: db
  namespace: flux-system
spec:
  chart:
    spec:
      chart: postgres
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: helm-repo-lfs269
  interval: 1m0s
  targetNamespace: instavote
  values:
    service:
      name: helmrelease-db
    settings:
      authMethod: trust
