---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: instavote
  namespace: flux-system
spec:
  gitImplementation: go-git
  interval: 1m
  ref:
    branch: main
  timeout: 20s
  url: https://github.com/Habibul786/instavote.git
