---
apiVersion: notification.toolkit.fluxcd.io/v1
kind: Receiver
metadata:
  name: instavote
  namespace: flux-system
spec:
  events:
  - ping
  - push
  resources:
  - kind: GitRepository
    name: instavot
  secretRef:
    name: webhook-token
  type: github
